#!/bin/bash
set -e

# File this script will modify
CONF_FILE="/etc/sddm.conf.d/zz-steamos-autologin.conf"

# Session, gamescope or plasma
SESSION="${1:-gamescope-session.desktop}"

cat <<EOF > "$CONF_FILE"
[Autologin]
Session="$SESSION"
EOF
