#!/bin/bash
set -e

DISPLAY_MANAGER="$(readlink -f /etc/systemd/system/display-manager.service \
                    | sed 's|.*/||')"

case "${DISPLAY_MANAGER%.service}" in
    plasmalogin) CONF_FILE="/etc/plasmalogin.conf.d/zz-steamos-autologin.conf";;
    sddm) CONF_FILE="/etc/sddm.conf.d/zz-steamos-autologin.conf";;
esac

# Don't do anything if system is using unsupported display manager
[[ -z "$CONF_FILE" ]] && exit 0

# Session, gamescope or plasma
SESSION="${1:-gamescope-session.desktop}"

cat <<EOF > "$CONF_FILE"
[Autologin]
Session=$SESSION
EOF
